font_size 20
modify_font cell_height 200%
modify_font strikethrough_position 150%

cursor_blink_interval 0
window_padding_width 10
hide_window_decorations titlebar-only
wayland_titlebar_color background
enable_audio_bell no

cursor_trail 20
cursor_trail_start_threshold 1
cursor_trail_decay 0.0 0.15

map cmd+enter # no-op instead of splitting window

# BEGIN_KITTY_THEME
include current-theme.conf
cursor #545c7e
cursor_text_color #c0caf5
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font Mono' postscript_name=JetBrainsMonoNFM-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
