- clean: ['~']

- link:
    ~/.agignore: agignore
    ~/.bash_profile: bash_profile
    ~/.bashrc: bashrc
    ~/.ctags: ctags
    ~/.dircolors: dircolors
    ~/.gitconfig: gitconfig
    ~/.gitignore_global: gitignore_global
    ~/.gvimrc: gvimrc
    ~/.jshintrc: jshintrc
    ~/.mutt/colorscheme-jess.muttrc:
        create: true
        path: mutt/colorscheme-jess.muttrc
    ~/.muttrc: muttrc
    ~/.ncmpcpp/config:
        create: true
        path: ncmpcpp.conf
    ~/.tmux: tmux
    ~/.tmux.conf: tmux.conf
    ~/.tmux_darwin.conf: tmux_darwin.conf
    ~/.tmux_linux.conf: tmux_linux.conf
    ~/.vim: vim/
    ~/.vimperatorrc: vimperatorrc
    ~/.vimrc: vimrc
    ~/.vimrc.bundles: vimrc.bundles
    ~/.vimrc.bundleconfig: vimrc.bundleconfig
    ~/.Xresources: Xresources

- shell:
    - [git submodule update --init --recursive, Installing submodules]
    - [vim +PluginClean! +PluginUpdate +qall, Installing Vim plugins]
    - [~/.vim/bundle/YouCompleteMe/install.sh, Building YouCompleteMe binaries]
    - [make --directory=~/.vim/bundle/tagbar-phpctags.vim/, Building tagbar-phpctags binaries]
    - [make --directory=~/.vim/bundle/vimproc.vim/, Building vimproc]
    - [~/.tmux/plugins/tpm/scripts/install_plugins.sh >/dev/null 2>&1, Installing tmux plugins]
